### ISSUE TITLE
Declaring a it block without a function body results in unexpected behaviour

### ISSUE THREAD

**Issue by Bangsadrengur** [agirorn/jasmine-vow#1]
Decarling a `it` block without a function body 
```
it('should work as expected);
```
should result in a pending test. When using jasmine-vow it results in a failed test with the following message
```
Message:
    TypeError: cb is not a function
  Stack:
    TypeError: cb is not a function
        at Object.callback (/path/to/project/node_modules/jasmine-vow/lib/wrap.js:12:23)
```
